name: musicpod
version: git
summary: Music, podcast and internet radio player
description: Play local audio files, browse podcasts online or listen to internet radio stations.
website: https://github.com/ubuntu-flutter-community/musicpod
contact: frederik.feichtmeier@gmail.com
source-code: https://github.com/ubuntu-flutter-community/musicpod
icon: snap/gui/musicpod.png

confinement: strict
base: core22
grade: stable
license: MPL-2.0

apps:
  musicpod:
    command: musicpod
    extensions: [gnome]
    plugs:
      - network
      - network-bind
      - network-control
      - alsa
      - audio-playback
      - network-manager-observe
      - home
      - browser-support
      - hostname-control
    slots:
      - mpris

slots:
  dbus-musicpod:
    interface: dbus
    bus: session
    name: org.feichtmeier.Musicpod

parts:
  musicpod:
    source: .
    source-type: git
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libunwind-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
